### ISSUE TITLE
App crashed when calling `connectToPrinter`

### ISSUE THREAD

**Issue by HualiangLI** [MythiCode/zebra_utlity#8]
I'm trying to connect a Zebra Printer with its Bluetooth mac address. And after calling `connectToPrinter` function, it crashed with the following info:
```
E/CrashReport(25839): java.lang.ClassCastException: java.lang.String cannot be cast to char[]
E/CrashReport(25839): 	at com.professor.zebrautility.Printer$11.run(Printer.java:643)
E/CrashReport(25839): 	at java.lang.Thread.run(Thread.java:784)
```

Additionally, the printer model is Zebra ZD888T

**Comment by santiago21ag** [comment]
@HualiangLI  Can you recommend any fluter plugin that has served you with zebra printers? I have problems printing with the zebra brand, can you please help me.
